-- =============================================
-- 투표 시스템 Supabase 테이블 스키마
-- =============================================

-- 1. 관리자 테이블
CREATE TABLE admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. 참여자(청중) 테이블
CREATE TABLE participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  department VARCHAR(100),
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. 발표자(팀) 테이블
CREATE TABLE presenters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name VARCHAR(100) UNIQUE NOT NULL,
  presenter_name VARCHAR(100) NOT NULL,
  topic VARCHAR(255),
  display_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 4. 투표 테이블
CREATE TABLE votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_id BIGINT REFERENCES participants(id) ON DELETE CASCADE,
  presenter_id BIGINT REFERENCES presenters(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE(participant_id, presenter_id)
);

-- 5. 설정 테이블
CREATE TABLE settings (
  id INT PRIMARY KEY DEFAULT 1,
  max_votes INT DEFAULT 5,
  voting_open BOOLEAN DEFAULT true,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 기본 설정 삽입
INSERT INTO settings (id, max_votes, voting_open) VALUES (1, 5, true);

-- =============================================
-- Row Level Security (RLS) 정책
-- =============================================

-- RLS 활성화
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenters ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- 모든 테이블에 대해 anon 사용자 읽기/쓰기 허용
-- (실제 운영 시에는 더 세밀한 정책 필요)

-- admins: 읽기만 허용 (로그인용)
CREATE POLICY "Allow read admins" ON admins FOR SELECT USING (true);

-- participants: 읽기/쓰기 허용
CREATE POLICY "Allow read participants" ON participants FOR SELECT USING (true);
CREATE POLICY "Allow insert participants" ON participants FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update participants" ON participants FOR UPDATE USING (true);
CREATE POLICY "Allow delete participants" ON participants FOR DELETE USING (true);

-- presenters: 읽기/쓰기 허용
CREATE POLICY "Allow read presenters" ON presenters FOR SELECT USING (true);
CREATE POLICY "Allow insert presenters" ON presenters FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update presenters" ON presenters FOR UPDATE USING (true);
CREATE POLICY "Allow delete presenters" ON presenters FOR DELETE USING (true);

-- votes: 읽기/쓰기 허용
CREATE POLICY "Allow read votes" ON votes FOR SELECT USING (true);
CREATE POLICY "Allow insert votes" ON votes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow delete votes" ON votes FOR DELETE USING (true);

-- settings: 읽기/쓰기 허용
CREATE POLICY "Allow read settings" ON settings FOR SELECT USING (true);
CREATE POLICY "Allow update settings" ON settings FOR UPDATE USING (true);
CREATE POLICY "Allow insert settings" ON settings FOR INSERT WITH CHECK (true);

-- =============================================
-- 테스트 데이터 (선택사항)
-- =============================================

-- 관리자 계정 추가 (사번: admin, 비밀번호: admin123)
-- INSERT INTO admins (employee_id, password) VALUES ('admin', 'admin123');

-- 샘플 발표자 추가
-- INSERT INTO presenters (team_name, presenter_name, topic, display_order) VALUES
-- ('AI혁신팀', '홍길동', 'AI 기반 업무 자동화', 1),
-- ('데이터팀', '김철수', '데이터 분석 플랫폼', 2),
-- ('클라우드팀', '이영희', '클라우드 마이그레이션', 3);
